### ISSUE TITLE
how to use burpsuite and tor ip changer at a time

### ISSUE THREAD

**Issue by gauravdeore98** [seevik2580/tor-ip-changer#47] opened 2021-07-09 16:44 UTC
how to use burpsuite and tor ip changer at a time
also toripchanger new exe file is corrupted after download every time

**Comment by seevik2580** [comment] 2021-07-10 01:30
hello,
to use burp suite with tor-ip-changer, you have to start tor-ip-changer first, then start TOR server with button in the top menu, then start burp suite app, set SOCKS proxy inside user options to 127.0.0.1 port 9050, then you are good to go.
also what do you mean exe is corrupted ? i tried it right now and everything works well. do you have any screenshots or more info about corruption ?

![image](https://user-images.githubusercontent.com/22060747/125147865-786bad80-e12e-11eb-9fd9-f0610e6ace5f.png)
![image](https://user-images.githubusercontent.com/22060747/125147869-802b5200-e12e-11eb-978b-95474d410ad9.png)

**Comment by gauravdeore98** [comment] 2021-07-10 03:51
https://user-images.githubusercontent.com/74418289/125150778-0f9d2900-e160-11eb-89d3-d451e965c5c2.mp4

**Comment by seevik2580** [comment] 2021-07-10 11:47
thats weird, i cannot reproduce this error. can you try to extract it with 7-zip ? also can you try to download updater.exe instead of ipchanger.rar ? updater.exe will download newest version of ipchanger for you and then you dont have to extract anything
[https://github.com/seevik2580/tor-ip-changer/blob/master/dist/updater.exe](https://github.com/seevik2580/tor-ip-changer/blob/master/dist/updater.exe)

**Comment by metinkalinsaz** [comment] 2021-07-11 12:43
Dude the exe for windows is corrupt. After uploading the files it won't open. Could it be an issue with the firewall? I tried with 7-zip, unfortunately it doesn't work. It may have been incompletely built. It says can't find MSVCR100.dll file.

**Comment by seevik2580** [comment] 2021-07-11 14:18
MSVCR100.DLL error means you are missing Microsoft Visual C++ 2010 Redistributable Package.. download and install x86 and x64 version. also exe is not corrupted, looks like there is something in your system which prevent you to run this program. firewall, antivirus, etc...

clip of downloading updater.exe
https://user-images.githubusercontent.com/22060747/125198674-385a1700-e263-11eb-9a83-d6ddbed2cc91.mp4

clip of downloading ipchanger.rar
https://user-images.githubusercontent.com/22060747/125198678-3bed9e00-e263-11eb-9ddd-197694dbb444.mp4

**Comment by gauravdeore98** [comment] 2021-07-11 14:26
its closing immediately after opening

https://user-images.githubusercontent.com/74418289/125199019-00ae9780-e282-11eb-882a-c395d7cb3eda.mp4

**Comment by metinkalinsaz** [comment] 2021-07-11 14:37
I downloaded version 1.2.6 and it works fine. There may be a bug between versions. The latest version gives an error, I downloaded the previous version and ran it.

**Comment by seevik2580** [comment] 2021-07-11 14:37
program does not close itself, something kills it. if program crashes itself there should be ipchanger.exe.log file which contains errors .. but its not. so there has to be something in your system which prevents you using this program.
try to create shortcut of ipchanger.exe and use option -d ... or use Command Prompt to start ipchanger with command `ipchanger.exe -d` from current directory

**Comment by seevik2580** [comment] 2021-07-11 14:45
> I downloaded version 1.2.6 and it works fine. There may be a bug between versions. The latest version gives an error, I downloaded the previous version and ran it.

ok thanks for report. difference between versions `1.2.6` and `1.2.7` is `1.2.6` version was compiled with `python 3.7` and version `1.2.7` was compiled with `python 3.4`... i will try to update version `1.2.7` and recompile it with `python 3.7` if this helps

**Comment by seevik2580** [comment] 2021-07-11 14:46
> > its closing immediately after opening
> > bandicam.2021-07-11.19-54-32-339.mp4
> 
> program does not close itself, something kills it. if program crashes itself there should be ipchanger.exe.log file which contains errors .. but its not. so there has to be something in your system which prevents you using this program.
> try to create shortcut of ipchanger.exe and use option -d ... or use Command Prompt to start ipchanger with command `ipchanger.exe -d` from current directory

@gauravdeore98 can you try version 1.2.6 as well ?

**Comment by gauravdeore98** [comment] 2021-07-11 14:56
1.2.6 worked now

**Comment by seevik2580** [comment] 2021-07-11 15:01
> 1.2.6 worked now

ok, can you try version 1.2.7 and after it closes itself, open settings.ini file and change line 
`disableupdates = no` to `disableupdates = yes` 
and let me know if this help

**Comment by gauravdeore98** [comment] 2021-07-11 15:05
1.2.7 is still not opening

**Comment by seevik2580** [comment] 2021-07-11 22:34
@gauravdeore98 @metinkalinsaz recompiled with python 3.7 can you test it ?
[3e22f89](https://github.com/seevik2580/tor-ip-changer/commit/3e22f89f98a511fe6755ff955bedd893b7181f00)

**Comment by gauravdeore98** [comment] 2021-07-12 03:32
it's worked now

**Closed** 2021-07-15 10:24 UTC
